### PR TITLE
upgrade to scala 2.13.0

### PR DESCRIPTION
**Pull request by mpollmeier**
Unfortunately we have a cyclic dependency with codepropertygraph, but
since it's only a test dependency I took the shortcut of publishing a
2.13 release for codepropertygraph which we use here. Once fuzzyc2cpg
is published for scala 2.13, we can release a normal cpg version which
we can depend on here.
Long term we should resolve the cyclic dependency.

### CODE REVIEW

**Comment by ml86** [comment]
And how is upgrading to 2.13 related to which problem caused by cyclic dependencies?

**Comment by mpollmeier** [comment]
Scala artifacts are published with a dependency on the scala major version (e.g. 2.12, 2.13).

Without dirty tricks I cannot build fuzzyc2cpg_2.13, because there is no codepropertygraph_2.13.
And I cannot do a normal release of codepropertygraph_2.13, because it's tests depend on fuzzyc2cpg_2.13. So the dirty trick was that i released a version of codepropertygraph_2.13 without having run (or even compiled) the tests. 

Note that this is only a problem with scala major releases, which happen every 1-2 years.

**Comment by ml86** [comment]
So this is part off an attempt to upgrade our code to scala 2.13?

**Comment by mpollmeier** [comment]
yes. doesn't sound like a good idea to you?

**Pull request merged**
